// packages/wujie-cli/template/examples/main-vue/src/views/Angular12.vue
<template>
  <WujieVue class="angular-container" name="angular12" :url="url" :attrs="attrs" :sync="true"></WujieVue>
</template>

<script>
import hostMap from "../../wujie-config/hostMap";

export default {
  data() {
    return {
      url: hostMap("//localhost:7400/"),
      // 修正iframe的url，防止github pages csp报错
      // attrs:
      //   process.env.NODE_ENV === "production"
      //     ? {
      //         src: hostMap("//localhost:7400/"),
      //       }
      //     : {},
    };
  },
};
</script>

<style lang="css" scoped>
.angular-container {
  width: 100%;
  height: 100%;
}
</style>

// create-wujie/template/examples/main-react/src/pages/Angular12.js
import React from "react";
import hostMap from "../hostMap.js";
import WujieReact from "wujie-react";
import { useNavigate } from "react-router-dom";

export default function Angular12() {
  const navigation = useNavigate();
  const angular12Url = hostMap("//localhost:7400/");
  const props = {
    jump: (name) => {
      navigation(`/${name}`);
    },
  };
  return (
    <WujieReact width="100%" height="100%" name="angular12" url={angular12Url} sync={true} props={props}></WujieReact>
  );
}
