// create-wujie/template/examples/main-vite/src/views/React16.vue
<template>
  <!--单例模式，name相同则复用一个无界实例，改变url则子应用重新渲染实例到对应路由 -->
  <WujieVue width="100%" height="100%" name="react16" :url="react16Url" :sync="true"></WujieVue>
</template>

<script>
import hostMap from "../wujie-config/hostMap";

export default {
  data() {
    return {
      react16Url: hostMap("//localhost:7600/"),
    };
  },
};
</script>

<style lang="scss" scoped></style>

// create-wujie/template/examples/main-react/src/pages/React16.js
import React from "react";
import hostMap from "../hostMap.js";
import WujieReact from "wujie-react";
import { useNavigate, useLocation } from "react-router-dom";

export default function React16() {
  const navigation = useNavigate();
  const location = useLocation();
  const path = location.pathname.replace("/react16-sub", "").replace("/react16", "").replace("/", ""); ////
  const react16Url = hostMap("//localhost:7600/") + path;
  const props = {
    jump: (name) => {
      navigation(`/${name}`);
    },
  };
  return (
    // 单例模式，name相同则复用一个无界实例，改变url则子应用重新渲染实例到对应路由
    <WujieReact width="100%" height="100%" name="react16" url={react16Url} sync={!path} props={props}></WujieReact>
  );
}
